# Generated by Django 4.0.6 on 2023-01-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagerapp', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
