# Generated by Django 4.0.6 on 2023-02-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagerapp', '0007_displayusername_remove_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayusername',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
