# Generated by Django 4.0.6 on 2023-02-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagerapp', '0008_alter_displayusername_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='displayusername',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
