# Generated by Django 4.0.6 on 2023-05-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagerapp', '0009_delete_displayusername_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='username',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_by',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
